### ISSUE TITLE
Can't Find StudioLuauTranspiler

### ISSUE THREAD

**Issue by naor020066** [ShouxTech/RobloxQuickXecute#4]
I can't find the StudioLuauTranspiler that you are using in your video. Is it another project you created? If so can you upload it too? Thanks in advance.

**Comment by ShouxTech** [comment]
Hello, I believe the StudioLuauTranspiler program just shifted some bytes in the regular (non Roblox client) Luau instructions by a certain amount in order to convert the bytecode into something that was usable in the Roblox client, but I don't remember exactly how it worked. Unfortunately I don't have it anymore and so I can not share it. I don't even know if it would still work since it's been a few years.
